# Blog Settings
title: '@goenning'
url: http://goenning.net
gravatar: http://www.gravatar.com/avatar/ba158e6c8c0e4a7869f4b9f0a45db0fe?s=200

# Discuss
disqus: true
disqus_user: goenning-net

# Twitter
twitter_share: true
twitter_user: goenning

# Jekyll Settings
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
paginate: 5
permalink: pretty
relative_permalinks: true
