# Blog Settings
title: '@goenning'
url: http://goenning.net

# Discuss
disqus: true
disqus_user: goenning-net

# Twitter
twitter_share: true
twitter_user: goenning

#
# Jekyll Settings
#
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
paginate: 5
permalink: pretty
relative_permalinks: true
