#
# This file contains configuration flags to customize your site
#
name: '@goenning'
description: loop at { code; run; read; blog; eat; bike ride; } until tired;
avatar: //www.gravatar.com/avatar/ba158e6c8c0e4a7869f4b9f0a45db0fe?s=200
env: production

#
# Flags below are optional
#

navigation:
  en:
    index:
      name: "Blog"
      url: "/"
    archive:
      name: "Archive"
      url: "/archive"
    about:
      name: "About"
      url: "/about"
  pt:
    index:
      name: "Blog"
      url: "/pt"
    archive:
      name: "Arquivo"
      url: "/arquivo"
    about:
      name: "Sobre"
      url: "/sobre"


# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: me@goenning.net
  facebook:
  flickr:
  github: goenning
  instagram:
  linkedin: goenning
  pinterest:
  rss: goenning
  twitter: goenning
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: goenning-net

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-47250005-3

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://goenning.net

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: pretty

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
