# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               '@goenning'
url:                 http://goenning.net
baseurl:             ''
paginate:            5

# Custom vars
version:             1.0.0

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
