# Blog Settings
title: '@goenning'
description: Where I blog about coding and some other awesome things
url: http://goenning.net
gravatar: http://www.gravatar.com/avatar/ba158e6c8c0e4a7869f4b9f0a45db0fe?s=200

author:
  name: Guilherme Oenning
  email: oenning.ti@gmail.com
  uri: http://goenning.net

# Discuss
disqus: true
disqus_user: goenning-net

# Twitter
twitter_share: true
twitter_user: goenning

# Jekyll Settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge

paginate: 5
permalink: pretty

# Plug-ins
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
